version: "3.8"
services:
  api:
    build: ./api
    container_name: learning-compose-api-c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  react-blogs:
    build: ./react-blogs
    container_name: learning-compose-react-blogs-c
    ports:
      - '3000:3000'
    volumes:
      - ./react-blogs:/app
      - /app/node_modules
    stdin_open: true
    tty: true